theme: jekyll-theme-minimal
title: skyearning's homepage
description: Bookmark this to keep an eye on my project updates!

on:
  push:
    branches:
      - master
name: "Trigger: Push action"
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
